### ISSUE TITLE
I found the matching speed is slow ( use superpoint+lightglue )

### ISSUE THREAD

**Issue by 16Huzeyu** [3DOM-FBK/deep-image-matching#10]
First of all, I would like to thank you for your work. However, when I was using it to process 1k images of 4k resolution, I noticed that the matching speed was very slow, around 3 pairs/s. I saw that you have mentioned speed improvements in your todo, and if there is any progress, I will follow up promptly.

**Comment by lcmrl** [comment]
Hi, are you using a brute-force approach? The best thing to do is to pre-process your images to match only the overlapping ones,. You have different options: 1. `--strategy matching_lowres` preprocesses everything at low resolution and then matches at high res only the overlapping images 2. `--strategy retrieval` `-r netvlad` (or other global descriptors) computes a global descriptor for each image and compare all image pairs selecting only the best pairs to be processing at high res. 3. if for any reason you know the pairs to be matched you can use `--strategy custom_pairs` and pass a txt file with the pairs `custom_pairs`. In general to be a bit faster in matching you can change the config.py, see the options of "superpoint+lightglue_tiling" and change `"quality": Quality.MEDIUM` to `"quality": Quality.HIGH`. Probably you need to download/pull the updated version of the repository.

**Comment by franioli** [comment]
Hi, in addition to Luca's answer, we know that there are some speed issues and we are working to find and reduce bottlenecks. Can you provide us some more information about the configuration that you are using? This may be helpful also for us for debugging.

For "configuration", I mean:

- dimensions of your image, if you are using a tiling approach and, in this case, the tiling grid and the tile selection method (GRID, PRESELECTION) and tile overlap.
- matching strategy (brute-force, sequential, retrieval) and in case of sequential the overlap 
- the superpoint and superglue configuration (if you are using one of the pre-defined configurations available in config.py or if you are using a custom one), in particular the maximum number of features that you are extracting (per image or per tile)

Finally, may I ask you how did you find the usage of the code so far?

**Comment by 16Huzeyu** [comment]
Thank you for your answers! @franioli @lcmrl 
I indeed use --strategy custom_pairs. And have tried superpoint+lightglue_fast ,it is almost 8xfatser but I need to test the quality .
I found the code just by search "colmap+deep" in github beacause I have faced the problem how to imporve colmap with some new methods of feature extraction and matching.
