### ISSUE TITLE
main.py not setting the 'use_pycolmap' variable when pycolmap successfully loaded

### ISSUE THREAD

**Issue by simonpokorny** [3DOM-FBK/deep-image-matching#19]
BUG REPORT: The current implementation in main.py lacks the definition of the use_pycolmap variable after a successful import of the pycolmap module. This omission occurs specifically on line 259, leading to potential issues in the subsequent execution of the code.

**Comment by lcmrl** [comment]
Hi, thanks to report the bug, now should be solved on the master branch. Let us know if you find any problem!
