### ISSUE TITLE
the Error when using 'loftr'

### ISSUE THREAD

**Issue by famersalltheday** [3DOM-FBK/deep-image-matching#21]
Hi, thank you for your solid work.
When I use 'loftr', will meet 'line 293, in _extract_by_tile, (kpts_full, feat_tile["keypoints"] + np.array(lim[0:2])), ValueError: operands could not be broadcast together with shapes (0,) (2,) '. 
Could you give me some advice, thank you.

**Comment by franioli** [comment]
Hi, we are sorry, it's a bug that occurs running LOFTR and RoMa using tiles. I'm currently working to fix it and I hope to release the fix soon.
In the meanwhile, you can run LOFTR on full images but with lower resolution (Quality.MEDIUM or Quality.LOW and TileSelection.NONE), this should work.
Thanks for the report

**Comment by famersalltheday** [comment]
thank you for you reply, well,I tried and met " line 108 feature_path = feats0['feature_path'] KeyError: 'feature_path' "

**Comment by lcmrl** [comment]
Hi,  thanks for reporting the issue. Could you try fetching the last version of the repository and pulling the changes? you should not encounter the problem using TileSelection.NONE. Let us know if you encounter any bug. Working to solve the problem on high resolution images and with TileSelection.PRESELECTION or TileSelection.GRID

**Comment by famersalltheday** [comment]
Thank you so much for your help. I have soved this error, due to the dependencies version.

**Comment by lcmrl** [comment]
Now loftr and roma work also using TileSelection.PRESELECTION. Let us know if you encounter any issues
