### ISSUE TITLE
Warning loading EXIF

### ISSUE THREAD

**Issue by lcmrl** [3DOM-FBK/deep-image-matching#38]
Extend warning description when EXIFs are not correctly imported.In any case, the warning does not affect the correct functioning of the software.

**Comment by franioli** [comment]
Fixed in [#b856c0f](https://github.com/3DOM-FBK/deep-image-matching/commit/b856c0f3d35cbaf6d87d90e312d7d2a97c53d0d6)

**Comment by franioli** [comment]
fixed in  [https://github.com/3DOM-FBK/deep-image-matching/commit/200ff9b1a16768238c93fee9eb1933744eea343b](https://github.com/3DOM-FBK/deep-image-matching/commit/200ff9b1a16768238c93fee9eb1933744eea343b)
