### ISSUE TITLE
How to check the matching result?

### ISSUE THREAD

**Issue by oUp2Uo** [3DOM-FBK/deep-image-matching#39]
Hi, I found some problem when processing my own data (large images).
When downsampled to 2K, position calcultion result is right. When downsampled to 2K, and processing with tiling preselection (tile_size is set to half of default, try_match_full_images set true), still OK.
But when downsampled to 4K, the result is wrong. When downsampled to 4K, and processing with tiling preselection (try_match_full_images set true or false both tested), still wrong.
It seems that processing of large images may have problem.

I guess if matching result is not good, and I want to debug this. 
Now I can find image pairs with features in folder `results_superpoint+lightglue_matching_lowres_quality_high/debug`.
But there is no matching result for debug. I have read the documents and still do not know how to check the matching results.
Is there a way to check this result?

Update: I have found `show_matches.py` in the root folder, but I cannot run it as the usage.
Error message is:
`ModuleNotFoundError: No module named 'cv2'`
I have tried to run `pip install opencv-python`, and got message:
```
Requirement already satisfied: opencv-python in c:\users\up2u\miniconda3\envs\deep-image-matching\lib\site-packages (4.9.0.80)
Requirement already satisfied: numpy>=1.17.0 in c:\users\up2u\miniconda3\envs\deep-image-matching\lib\site-packages (from opencv-python) (1.26.3)
```

Thank you.

**Comment by lcmrl** [comment]
Hi, to debug the easier way is to use COLMAP GUI. Please check here for COLMAP installation (https://colmap.github.io/install.html). Then
- run COLMAP GUI
- `File` tab > `New project`
- Click `Database` `Open` (not `New`), and select the database (.db format) that you can find in the results folder
- Click `Images` `Select` - select the folder with images that you used
- Click `Save`
- `Processing` tab > `Database Management`
- Click an image > click on the top right `Overlapping images`
- Click `Two-view geometries` tab
- Click an overlapping image and then `Show matches`
Let me know if you manage to debug

**Comment by oUp2Uo** [comment]
Thanks for your reply.
I run in the same console which I run `main.py`, and got the error `ModuleNotFoundError: No module named 'cv2'`.

**Comment by lcmrl** [comment]
Ok good, please let us know if there is an issue on the matches downsampling the images

**Comment by oUp2Uo** [comment]
Hi, I have checked some pairs, and found matching result is quite differenet when images are 2K or 4K.

For example,

2K 
![2010_2013_2K_small](https://github.com/3DOM-FBK/deep-image-matching/assets/29222415/f97c5cc5-2434-4894-a52b-9e691a5a5832)

4K
![2010_2013_4K_small](https://github.com/3DOM-FBK/deep-image-matching/assets/29222415/1bda005c-d65b-451a-99f3-6533c028f2a5)

When the image is 4K size, the light before the main object is mis-matched. 
There are fewer feature points on the main object, and almost no pairs between the main object of two images.

**Comment by lcmrl** [comment]
Could you share the command you used? I imagine preselection is none and you are using superpoint+lightglue?

**Comment by oUp2Uo** [comment]
I just run `python main.py --dir xxxxx --pipeline superpoint+lightglue` in the readme doc.
Also, I have tried to copy the `config/superpoint+lightglue.yaml` file to the base folder, and then run `python main.py --dir xxxxx --pipeline superpoint+lightglue - c config.yaml`. (Once I tried to add `try_match_full_images` option when tiling and still no good result.)
When processing 4K images, I have both tried to run with/without `preselection`, and both could not get good result.

I will try some other large images data to see if they have the same problem.

**Comment by lcmrl** [comment]
If you want you can share a folder with the two images of the statue (full resolution), so that I can give a look

**Comment by oUp2Uo** [comment]
Thanks for your help.
Image ZIP file is larger than 25MB (18 images), could not upload here.
I have uploaded it to https://gigafile.nu/, which can temporarily saving files.
Here is the download link: https://53.gigafile.nu/0510-p1cc7f950c7d23246eed74a7bada1804c
password: 1234

Sorry for using a Japanese language website, here is the usage:
Input password in the left box, then click the button, download will start.
![download](https://github.com/3DOM-FBK/deep-image-matching/assets/29222415/54efc16b-17bd-409b-9b3e-173633391374)

**Comment by oUp2Uo** [comment]
I think I may find the reason.
When processing large images, `extractor` parameter `max_keypoints` may need to set larger.
Otherwise, most of the points may go to the background, not on the main object.
When I try 4K images, with `max_keypoints` set to 32000, the result is almost same with 2K images with `max_keypoints` 8000 as default.

**Comment by lcmrl** [comment]
Good, sorry I didn't have time to check the images yet. It sounds reasonable, keypoints are extracted based on a score and the texture of 4K can be much more rich than 2K and keypoints can be not extracted uniformly. A simple way to have more distributed keypoints is working by tiles. Thanks for the feedbacks, feel free to open other issues or to collaborate to the project!
