### ISSUE TITLE
Switching from SIMPLE_RADIAL to PINHOLE Camera Model Causes AttributeError in pycolmap

### ISSUE THREAD

**Issue by helloycr** [3DOM-FBK/deep-image-matching#46]
Hello, thank you very much for making your work open source!! However, I encountered some problems when switching from the SIMPLE_RADIAL camera model to the PINHOLE camera model. Could you please help me take a look?

In the main.py file, I changed:
```python
if use_pycolmap:
    # import reconstruction module
    reconstruction = import_module("src.deep_image_matching.reconstruction")
    # Define database path
    database = output_dir / "database_pycolmap.db"
    camera_mode = pycolmap.CameraMode.AUTO
    cameras = []
```
to:
```python
    if use_pycolmap:
        # import reconstruction module
        reconstruction = import_module("src.deep_image_matching.reconstruction")

        # Define database path
        database = output_dir / "database_pycolmap.db"

        camera_mode = pycolmap.CameraMode.SINGLE
        cam0 = pycolmap.Camera(
            model="PINHOLE",
            width=1500,
            height=1000,
            params=[1500, 1500, 750, 500],
         )
       cameras = [cam0] 
```

But when I run the main.py file with `python main.py --dir assets/example_cyprus --pipeline superpoint+lightglue`, I get an error:
```
Traceback (most recent call last):
  File "/home/cashap/code/SFM/deep-image-matching/main.py", line 137, in <module>
    model = reconstruction.main(
  File "/home/cashap/code/SFM/deep-image-matching/src/deep_image_matching/reconstruction.py", line 143, in main
    update_cameras(database, cameras)
  File "/home/cashap/code/SFM/deep-image-matching/src/deep_image_matching/reconstruction.py", line 66, in update_cameras
    camera_id, cam.model_id, cam.width, cam.height, cam.params, True
AttributeError: 'pycolmap.Camera' object has no attribute 'model_id'
```

Based on the error message, here is the part of the code where the error was located:
```python
def update_cameras(database_path: Path, cameras: [List[pycolmap.Camera]]):
    if not all([isinstance(cam, pycolmap.Camera) for cam in cameras]):
        raise ValueError("cameras must be a list of pycolmap.Camera objects.")

    db = COLMAPDatabase.connect(database_path)

    num_cameras = len(db.execute("SELECT * FROM cameras;").fetchall())
    if num_cameras != len(cameras):
        raise ValueError(
            f"Number of cameras in the database ({num_cameras}) "
            f"does not match the number of cameras provided ({len(cameras)})."
        )

    for camera_id, cam in enumerate(cameras, start=1):
        db.update_camera(
            camera_id, cam.model_id, cam.width, cam.height, cam.params, True
        )
    db.commit()
    db.close()
```

How should this problem be handled? Did I modify the code incorrectly, or are there parts that I missed to modify?

Thank you very much for your work, and I look forward to your reply! I am very grateful!!

**Comment by lcmrl** [comment]
Hi, thanks for the feedback. Do you still have the problem? Probably is related to the new version of pycolmap. Please, change in  src/deep_image_matching/reconstruction.py the following:
```
     for camera_id, cam in enumerate(cameras, start=1):
         db.update_camera(
-            camera_id, cam.model_id, cam.width, cam.height, cam.params, True
+            camera_id, cam.model.value, cam.width, cam.height, cam.params, True
         )
     db.commit()
     db.close()
```
this should do the work. Let me know if you still encounter the issue

**Comment by lcmrl** [comment]
Hi, I have added this change in `dev` branch, soon we will merge to `main`. Let me know if you face other problems

**Comment by helloycr** [comment]
Hello, I am operating according to your suggestion, but it still does not work.
`AttributeError: 'pycolmap.Camera' object has no attribute 'model'`

**Comment by helloycr** [comment]
@lcmrl @tudipffmgt @franioli
Hello, thank you for your reply! I followed your advice, but it still didn't work.
AttributeError: 'pycolmap.Camera' object has no attribute 'model'

**Comment by lcmrl** [comment]
Are you using the last version of pycolmap? On windows or linux?

**Comment by helloycr** [comment]
> 您使用的是最新版本的 pycolmap 吗？在windows还是linux上？

linux(Ubuntu18.04，CUDA11.8)

**Comment by lcmrl** [comment]
and pycolmap 0.6.1?

**Comment by lcmrl** [comment]
Could you try to uninstall pycolmap and reinstall it so that it will be the last one 0.6.1? This should do the trick
