### ISSUE TITLE
Show matches result error with RootSIFT local features

### ISSUE THREAD

**Issue by wuyingxiong** [3DOM-FBK/deep-image-matching#60]
Thanks for your work!
I use the colmap gui to visual the matches,and result is right,which means the match process(database.db) is right.But I use the show_matches.py to visual the matches. I get wrong result.
After debugging,I find that some keypoints have negative coordinate values.，which makes me confused.
How can I solve this problem？

![image](https://github.com/3DOM-FBK/deep-image-matching/assets/59959709/6a614fc4-ca24-47c5-a191-0f7a3c7a00c1)
![image](https://github.com/3DOM-FBK/deep-image-matching/assets/59959709/9182d8c9-01f4-4723-8d07-9d562b8c30fd)
![image](https://github.com/3DOM-FBK/deep-image-matching/assets/59959709/ef0a963b-2fb3-4c07-9c9f-744a1c5cdd37)

**Comment by lcmrl** [comment]
Hi, thanks for the feedback! To reproduce the error, are you on `master` or `dev` branch? Which local feature are you using (SP+LG)?

**Comment by wuyingxiong** [comment]
Thanks for your quick reply! I produce the database.db using the traditional colmap command and want to visualize the matches by show_matches.py.As for branch,I just follow the installation (git clone .....) ,the default is master.
colmap command follows:
```
    ## Feature extraction
    feat_extracton_cmd = colmap_command + " feature_extractor "\
        "--database_path " + args.source_path + "/distorted/database.db \
        --image_path " + args.source_path + "/input \
        --ImageReader.single_camera 1 \
        --ImageReader.camera_model " + args.camera + " \
        --SiftExtraction.use_gpu " + str(use_gpu)
    ## Feature matching
    feat_matching_cmd = colmap_command + " exhaustive_matcher \
        --database_path " + args.source_path + "/distorted/database.db \
        --SiftMatching.use_gpu " + str(use_gpu)
        
    mapper_cmd = (colmap_command + " mapper \
        --database_path " + args.source_path + "/distorted/database.db \
        --image_path "  + args.source_path + "/input \
        --output_path "  + args.source_path + "/distorted/sparse \
        --Mapper.ba_global_function_tolerance=0.000001")
   img_undist_cmd = (colmap_command + " image_undistorter \
    --image_path " + args.source_path + "/input \
    --input_path " + args.source_path + "/distorted/sparse/0 \
    --output_path " + args.source_path + "\
    --output_type COLMAP")
```

**Comment by lcmrl** [comment]
The reason is that sift keypoints from colmap are not (N_features x 2) but (N_features x 6), so you have to change `show_matches.py` like this:
line 55 `(image_id, blob_to_array(data, np.float32, (-1, 2)))` -> `(image_id, blob_to_array(data, np.float32, (-1, 6)))`
line 92 `keypoints0 = self.keypoints[id0]` -> `keypoints0 = self.keypoints[id0][:,:2]`
line 93 `keypoints1 = self.keypoints[id1]` -> `keypoints1 = self.keypoints[id1][:,:2]`
This should solve the problem. When using SuperPoint or other features, you should not encounter the problem

**Comment by wuyingxiong** [comment]
Thanks a lot ！ I'll try it right now

**Comment by wuyingxiong** [comment]
![image](https://github.com/3DOM-FBK/deep-image-matching/assets/59959709/a9378a2a-8d0a-482e-84aa-3fdd78e82b15)
absolutely right！

**Comment by lcmrl** [comment]
Good! Feel free to collaborate to the project, or open an issue if you find any problem
