### ISSUE TITLE
What is the distance unit of the generated file?

### ISSUE THREAD

**Issue by JV-X** [3DOM-FBK/deep-image-matching#64]
I am using the output of `deep-image-matching` as the input of `openMVS`. When I get the camera pose and point cloud and try to calculate the distance from the camera to the point for further calculation, I find that I cannot know the unit of the distance. I raised the question in the issue of the `openMVS` project, and the maintainer told me that `openMV`S did not change the unit, and the unit was determined during SfM. So I am here to ask a question, how to determine the length unit of `deep-image-matching` output?

This is the link where I asked a question in `openMVS`: 
https://github.com/cdcseacave/openMVS/issues/1145

**Comment by lcmrl** [comment]
Hi, SfM determines the geometry of the camera network and the scene up to a scale factor, so you have to use other known info from the "world" to scale the model: for instance the relative distance of a pair of cameras (or more), or of some points in the object space. So is normal the output of DIM is not "metric". If you have it, you can reference (and scale) the model using the 3D known position of some cameras and/or 3D points

**Comment by JV-X** [comment]
> Hi, SfM determines the geometry of the camera network and the scene up to a scale factor, so you have to use other known info from the "world" to scale the model: for instance the relative distance of a pair of cameras (or more), or of some points in the object space. So is normal the output of DIM is not "metric". If you have it, you can reference (and scale) the model using the 3D known position of some cameras and/or 3D points

thanks for your reply

**Comment by lcmrl** [comment]
Feel free to open other issues and to collaborate to the project!
