### ISSUE TITLE
Why the homography matrix all elements are equal to ones?

### ISSUE THREAD

**Issue by Abbsalehi** [3DOM-FBK/deep-image-matching#66]
I read database.db using pycolmap, but when I form two_view_geometry using two image ids, the homography matrix all elements equal to ones.
```
reconstruction= pycolmap.Database(database_path)
two_view_geometry= reconstruction.read_two_view_geometry(1, 2)
H = two_view_geometry.H
```

**Comment by franioli** [comment]
Hi, did you use pycolamp (or COLMAP from the GUI) to run the reconstruction or did you just run the matching with DIM?
At the moment, DIM does not write either the H, F, or E matrixes in the two_view_geometry table, but by default, it fills the keypoints and matches tables. 
Additionally, if a geometric verification (e.g., with pydegensac) is run, we also store the inliers matches in the two_view_geometry table, but we currently do not store the F matrix (this may be an improvement for the next release).
Anyway, if you run a reconstruction with pycolmap or from the GUI, then the F and E matrixes in the two_view_geometry table are estimated and stored in the database as usual.

**Comment by lcmrl** [comment]
Hi, I close the issue for inactivity. Feel free to reopen, any feedback or collaboration are welcome!
