### ISSUE TITLE
Cannot see any matches between the two images when using loftr. 

### ISSUE THREAD

**Issue by abhi1625** [3DOM-FBK/deep-image-matching#70]
Hi, 

I'm not able to see any matches drawn when using loftr for two images. I tried using the example images as well. Still don't see any matches. I use the `./scripts/show_matches.py` script for the examples_cyprus but I can only see the keypoints images and no matches. 

I'm I doing something wrong here? Please help.
![1_2](https://github.com/user-attachments/assets/46faa10e-78c4-4fa8-b7cc-11a60a9a52c1)

**Comment by lcmrl** [comment]
Thanks, for reporting, I will look into it. Have you tried to visualize them directly in COLMAP GUI? Importing the database

**Comment by lcmrl** [comment]
Ok there was an unhandled situation when raw matches missing. You can find the updated script in the "SRIF" branch, soon I will join it into `dev` branch. Thanks for reporting!
