### ISSUE TITLE
Inference too long time

### ISSUE THREAD

**Issue by silence-moon** [3DOM-FBK/deep-image-matching#71]
Thanks for your great work.
When I tried to run it in my computer, it takes long time to matching. I'd like to known why it run so long time, and there is any solution to decrease it?
My cuda version is 12.2 and the programe occupy 1.5G GPU memory.
The command "python main.py --dir ~/data/ --pipeline superpoint+lightglue --force" is used to run.
![2024-08-29 17-19-29屏幕截图](https://github.com/user-attachments/assets/56491b5a-00ba-4cb8-a55c-fdfc375cf077)

**Comment by lcmrl** [comment]
Hi, do you still have the problem? Which is the size of the images. Seems too slow for 512 images

**Comment by lcmrl** [comment]
DL features are quite computational expensive, in general to decrease the computational time there are different solutions:
- reduce the number of keypoints extracted per image defined in config files (or reduce image quality with the `--quality` option if the image is high resolution, but you can expect potentially a reduction of accuracy)
- use a different matching option, for instance global descriptors (see [documentation](https://3dom-fbk.github.io/deep-image-matching/getting_started/))

Thanks for reporting, please feel free to reopen the issue
