### ISSUE TITLE
Some problem about install

### ISSUE THREAD

**Issue by SirJackYang** [3DOM-FBK/deep-image-matching#73]
Hello, I have a question.
    I installed the deep-image-matching by "pip install -e ." in my conda env. But when I try to use pyinstaller to build my project, deep-image-matching will not be packaged.

**Comment by franioli** [comment]
Hi,
Can you provide us some more information on the error you have (e.g., screenshot of the terminal output)?

**Comment by SirJackYang** [comment]
![image](https://github.com/user-attachments/assets/4b2f60ad-1d18-4454-a318-ad7a7c85a5b1)

**Comment by SirJackYang** [comment]
![image](https://github.com/user-attachments/assets/a7dc6659-aa65-46dc-9186-0c7c9a541709)

**Comment by SirJackYang** [comment]
And my python version is 3.11.9, I removed "pydegensac" here manually.
![image](https://github.com/user-attachments/assets/29e32193-8373-4520-a9da-8f46bc1cad74)

**Comment by lcmrl** [comment]
Hope that did you solve the installation problem, feel free to reopen the issue!
