### ISSUE TITLE
mask

### ISSUE THREAD

**Issue by SamueleBumbaca** [3DOM-FBK/deep-image-matching#77]
First of all, thank you for this spectacular project,

I found this scripts/apply_masks.py and I was wondering if it is possible to apply masks (alpha channel or whatever) to images to perform feature extraction and matching only on the inner mask.

Thank you again

**Comment by lcmrl** [comment]
Hi, yes you can, for now the idea is super basic. It simply applies a uniform color in the areas where you do not want keypoints, so the dectors (handcrafted or not it will extract keypoints in other areas), then pass to the `./main.py` script the path to the new images with the applied mask.

**Comment by SamueleBumbaca** [comment]
Thank you (Grazie mille!)

**Comment by lcmrl** [comment]
Ciao, se trovi problemi facci sapere! e in generale sentiti libero di collaborare al progetto!
